### ISSUE TITLE
Highlight uBO's `!#else` directive condition

### ISSUE THREAD

**Issue by MasterKia** [AdguardTeam/VscodeAdblockSyntax#115]
```adb
!#if cap_html_filtering
example.com##^script:has-text(fakeAd)
!#else
example.com##+js(rmnt, script, fakeAd)
!#endif
```

Commit: https://github.com/gorhill/uBlock/commit/194354cd5d776f99c10381102afea13e5d018756

**Comment by scripthunter7** [comment]
Fixed in https://github.com/AdguardTeam/VscodeAdblockSyntax/commit/39ced9cc1dd819535e084742a262a160d7ce3e0b
