### ISSUE TITLE
Highlight `strict1p`, `strict3p`, `doc`, `header` and `beacon`

### ISSUE THREAD

**Issue by MasterKia** [AdguardTeam/VscodeAdblockSyntax#69]
```adb
||example.com^$xhr,strict1p,strict3p
||example.com^$strict3p
```

<details>

<summary>Show screenshot</summary>

![image](https://github.com/AdguardTeam/VscodeAdblockSyntax/assets/57285466/cdaf0e09-e1ce-4489-8366-91fb46e889eb)

</details>

Ideally the word "strict" should also be highlighted.

**Comment by slavaleleka** [comment]
@MasterKia `beacon` is an alias for `ping`, right?

**Comment by scripthunter7** [comment]
https://github.com/gorhill/uBlock/blob/eb52d46afa7fc2c55e3c3555e7c7bee8f136473c/src/js/static-net-filtering.js#L116-L117
