### ISSUE TITLE
Release guide

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/VscodeAdblockSyntax#73]
As soon as we are ready with the release workflow, we should prepare a release guide that describes the steps. These are basically the following:
- increase version
- filling changelog
- push `v*` tag

**Comment by ameshkov** [comment]
@scripthunter7

I'll add it before publishing the new update.

Do you think we should put it in the `CONTRIBUTING.md`?

**Comment by scripthunter7** [comment]
@ameshkov 

I thought about putting this chapter in `CONTRIBUTING.md`, but I think it would be a better idea to put it in `docs/releasing.md`.

I think the release process should be automated first (I created the workflow for this), and then something similar to [ECSSTree's releasing guide](https://github.com/AdguardTeam/ecsstree/blob/main/README.md#releasing-a-new-version) should be written here.

**Comment by scripthunter7** [comment]
@ameshkov I sent you the workflow in a private message
