### ISSUE TITLE
Publish the extension on open-vsx.org for VSCodium

### ISSUE THREAD

**Issue by MasterKia** [AdguardTeam/VscodeAdblockSyntax#91]
Since the VSCode binary from Microsoft is under a proprietary license and has built-in telemetry, there's VSCodium; a free/libre build without those problems.

Unfortunately, as Microsoft [prohibits usages of the Microsoft marketplace by any other products](https://github.com/microsoft/vscode/issues/31168) or redistribution of `.vsix` files from it, in order to use VSCode extensions in non-Microsoft products those need to be installed differently.

By default, VSCodium is set up to use [open-vsx.org](https://open-vsx.org/) as extension gallery, which has an [adapter](https://github.com/eclipse/openvsx/wiki/Using-Open-VSX-in-VS-Code) to the Marketplace API used by VSCode.

Could you publish this extension on [open-vsx.org](https://open-vsx.org) so that it could also be used on VSCodium?

Guide:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Thank you.

**Comment by scripthunter7** [comment]
@MasterKia Now the add-on is also available on Open VSX: https://open-vsx.org/extension/adguard/adblock

Happy coding!
