### ISSUE TITLE
Fix escaped commas in uBO scriptlet parameters

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/VscodeAdblockSyntax#95]
Escaped commas are highlighted incorrectly.

Example rule:

```adblock
##+js(trusted-set-cookie, gravitoData, {"NonTCFVendors":[{"id":1\,"name":"Facebook"\,"consent":true}\,{"id":3\,"name":"Google"\,"consent":true}\,{"id":9\,"name":"Twitter"\,"consent":true}]}, 1year)
```

from https://github.com/uBlockOrigin/uAssets/blob/a7d6966930f7648d9cc5740f5b03fb05f86029d4/filters/annoyances-cookies.txt#L63

<details>

<summary>Show screenshot</summary>

![image](https://github.com/AdguardTeam/VscodeAdblockSyntax/assets/57285466/28aa4e38-da3a-49d8-9b23-d9b83e66e97e)

</details>

Reported by @peace2000

**Comment by peace2000** [comment]
@scripthunter7 @slavaleleka On my end this doesn't seem to be fixed despite a month has passed.

Still escaped commas are shown red: https://github.com/uBlockOrigin/uAssets/blob/a7d6966930f7648d9cc5740f5b03fb05f86029d4/filters/annoyances-cookies.txt#L63

Also, now as uBO has started to support using quotes in values https://github.com/uBlockOrigin/uAssets/blob/562d4c6043f38ec3786dc34119d26e711140d6cf/filters/annoyances-cookies.txt#L124 I see that the quoted value still has commas colored in red.

**Comment by scripthunter7** [comment]
@peace2000

> Still escaped commas are shown in red: https://github.com/uBlockOrigin/uAssets/blob/a7d6966930f7648d9cc5740f5b03fb05f86029d4/filters/annoyances-cookies.txt#L63

GitHub highlighter takes time to update, you can learn more at https://github.com/AdguardTeam/VscodeAdblockSyntax#reporting-issues

> Also, now as uBO has started to support using quotes in values https://github.com/uBlockOrigin/uAssets/blob/562d4c6043f38ec3786dc34119d26e711140d6cf/filters/annoyances-cookies.txt#L124 I see that the quoted value still has commas colored in red.

At first glance, this appears to be a new issue that needs to be fixed, since this feature is not yet supported by the highlighter.

> However, there seems to be no issues in quoted AG values for some reason https://github.com/AdguardTeam/AdguardFilters/blob/2c9040591d31c180b99e2a599e7150a7b5c7a2a5/AnnoyancesFilter/Cookies/sections/cookies_specific.txt#L232

Yes, because the two types of scriptlet parameter management are a little different.

**Comment by peace2000** [comment]
Oh okay. Thanks for the info.
